### ISSUE TITLE
Error loading data: Cannot open fact file balance.facts

### ISSUE THREAD

**Issue by banescusebi** [eth-sri/securify2#11]
When running this command for a flattened contract:
```
sudo docker run -it -v <contract-dir-full-path>:/share securify /share/<contract>.sol
```
I get the following error: 
```
pragma directive defines a prior version to 0.5.12. Changing pragma version to 0.5.12....
Traceback (most recent call last):
  File "securify/__main__.py", line 286, in <module>
    main()
  File "securify/__main__.py", line 277, in main
    matches.extend(pattern.find_matches())
  File "/sec/securify/analyses/patterns/static/static_analysis_patterns.py", line 73, in find_matches
    static = analysis_context.static_analysis
  File "/sec/securify/analyses/analysis.py", line 88, in static_analysis
    self._static = self.config.static_analysis(self)
  File "securify/__main__.py", line 255, in <lambda>
    static_analysis=lambda t: static_analysis.analyze_cfg(t.cfg, **souffle_config),
  File "/sec/securify/staticanalysis/static_analysis.py", line 124, in analyze_cfg
    souffle_kwargs=kw_args_souffle)
  File "/sec/securify/staticanalysis/souffle/souffle.py", line 62, in run_souffle
    **(souffle_kwargs or {}))
  File "/sec/securify/staticanalysis/souffle/wrapper.py", line 141, in souffle_wrapper
    stderr_data=codecs.decode(stderrdata),
securify.staticanalysis.souffle.exceptions.SouffleError: Error during souffle execution:  

Error loading data: Cannot open fact file balance.facts
```

Has anyone seen this before?

**Comment by YannisSach** [comment]
Unfortunately, I am not sure what is the issue here. Could you try using the develop branch instead? If this does not fix the issue could you provide more information regarding the contract you are trying to test?
