### ISSUE TITLE
securify.staticanalysis.souffle.exceptions.SouffleError: Error during souffle execution

### ISSUE THREAD

**Issue by supuo** [eth-sri/securify2#23]
ENVIRONMENT:
solc version: 0.5.16
python version: 3.7.5
souffle version: 1.6.2
os: ubuntu 18.04

ERROR:
(venv) test@ubuntu:~$ securify Jump.sol 
libfunctors.so not compiled. Compiling it now...
Executable not found. Compiling it now. This might take some time...
Traceback (most recent call last):
  File "/home/test/venv/bin/securify", line 33, in <module>
    sys.exit(load_entry_point('securify', 'console_scripts', 'securify')())
  File "/home/test/securify2/securify/__main__.py", line 277, in main
    matches.extend(pattern.find_matches())
  File "/home/test/securify2/securify/analyses/patterns/static/static_analysis_patterns.py", line 73, in find_matches
    static = analysis_context.static_analysis
  File "/home/test/securify2/securify/analyses/analysis.py", line 88, in static_analysis
    self._static = self.config.static_analysis(self)
  File "/home/test/securify2/securify/__main__.py", line 255, in <lambda>
    static_analysis=lambda t: static_analysis.analyze_cfg(t.cfg, **souffle_config),
  File "/home/test/securify2/securify/staticanalysis/static_analysis.py", line 124, in analyze_cfg
    souffle_kwargs=kw_args_souffle)
  File "/home/test/securify2/securify/staticanalysis/souffle/souffle.py", line 62, in run_souffle
    **(souffle_kwargs or {}))
  File "/home/test/securify2/securify/staticanalysis/souffle/wrapper.py", line 119, in souffle_wrapper
    stderr_data=codecs.decode(stderrdata),
securify.staticanalysis.souffle.exceptions.SouffleError: Error during souffle execution:  

Warning: No rules/facts defined for relation patternIncorrectInequalityPattern.compliantInContext in unknown source location.
Warning: Variable comment only occurs once in unknown source location.
Warning: Variable ctxString only occurs once in unknown source location.
Warning: No rules/facts defined for relation patternUnusedStateVariablePattern.compliance in unknown source location.
Warning: Variable callerFunction only occurs once in unknown source location.
Warning: Variable callerFunction only occurs once in unknown source location.
Warning: Variable callerTransfers only occurs once in unknown source location.
Warning: Variable callerTag only occurs once in unknown source location.
Warning: Variable thisBlock only occurs once in unknown source location.
Warning: No rules/facts defined for relation warnings in unknown source location.
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to locate souffle-compile

**Comment by enderphan94** [comment]
Same issue

**Comment by qiikaii** [comment]
Is there any solution for this?

**Comment by enderphan94** [comment]
> Is there any solution for this?

Just re-installed the whole thing in Ubuntu, still got this issue.

souffle worked, solc worked... still error
